# MySQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: emart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# MongoDB PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emongo-pvc
  namespace: emart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi