# Ingress for frontend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  namespace: emart
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-svc
            port:
              number: 4200

      # - pathType: Prefix
      #   path: "/api"
      #   backend:
      #     service:
      #       name: api-svc
      #       port:
      #         number: 5000
      # - pathType: Prefix
      #   path: "/webapi"
      #   backend:
      #     service:
      #       name: webapi-svc
      #       port:
      #         number: 9000
