# Frontend Client Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-svc
#   namespace: emart
# spec:
#   type: ClusterIP
#   selector:
#     app: client
#   ports:
#   - port: 4200
#     targetPort: client-port
#     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: emart
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  selector:
    app: client
  ports:
  - port: 80



